apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fanout-ingress
spec:
  rules:
  - host: booksearcher.codemonkey.zone
    http:
      paths:
      - backend:
          serviceName: booksearcher-prod
          servicePort: 8080
  - host: booksearchercanary.codemonkey.zone
    http:
      paths:
      - backend:
          serviceName: booksearcher-canary
          servicePort: 8080