openapi: "3.0.0"
info:
  version: 1.0.0
  title: Book Searcher
security:
  - ApiKeyAuth: []
servers:
  - url: http://localhost/v1
paths:
  /books/{isbn}:
    get:
      summary: Info for books
      tags:
        - book
      parameters:
        - name: isbn
          description: isbn10 or isbn13
          in: path
          required: true
          style: simple
          schema:
            type: string
          example: 0375725784,9780375725784
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Books"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"    
components:
  securitySchemes:
    ApiKeyAuth:        # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: X-API-KEY  # name of the header, query parameter or cookie
  schemas:
    Book: 
      properties:
        isbn13:
          type: string
          minLength: 13
          maxLength: 13
        isbn10:
          type: string
          minLength: 10
          maxLength: 10
        title:
          type: string
        pages:
          type: integer
        author:
          type: array
          items:
            type: string
        publishDate:
          type: string
          format: date
          description: https://swagger.io/docs/specification/data-models/data-types/#string
        language:
          type: string
        publisher:
          type: string

    Books:
      type: array
      items:
        $ref: "#/components/schemas/Book"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string